/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'charcoal': '#111111',
        'slate': '#1a1a1a',
        'platinum': '#e0e0e0',
        // Theme-aware colors via CSS variables
        'obsidian': 'rgb(var(--color-bg-primary) / <alpha-value>)',
        'steel': 'rgb(var(--color-bg-secondary) / <alpha-value>)',
        'pearl': 'rgb(var(--color-text-primary) / <alpha-value>)',
        'silver': 'rgb(var(--color-text-secondary) / <alpha-value>)',
        'line': 'rgb(var(--color-border) / <alpha-value>)',
        'accent': {
          DEFAULT: '#06b6d4',
          50: '#ecfeff',
          100: '#cffafe',
          200: '#a5f3fc',
          300: '#67e8f9',
          400: '#22d3ee',
          500: '#06b6d4',
          600: '#0891b2',
          700: '#0e7490',
          800: '#155e75',
          900: '#164e63',
        },
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.8s ease-out',
        'slide-down': 'slideDown 0.8s ease-out',
        'scale-in': 'scaleIn 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(var(--grid-line-color) 1px, transparent 1px), linear-gradient(90deg, var(--grid-line-color) 1px, transparent 1px)',
        'dot-pattern': 'radial-gradient(circle, rgba(6, 182, 212, 0.08) 1px, transparent 1px)',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      backgroundSize: {
        'grid': '60px 60px',
        'dot': '24px 24px',
      },
      typography: {
        DEFAULT: {
          css: {
            color: 'rgb(var(--color-text-secondary))',
            maxWidth: '72ch',
            lineHeight: '1.8',
            a: {
              color: '#06b6d4',
              textDecoration: 'underline',
              textDecorationColor: 'rgba(6, 182, 212, 0.3)',
              textUnderlineOffset: '3px',
              '&:hover': { color: '#22d3ee', textDecorationColor: '#22d3ee' },
            },
            strong: { color: 'rgb(var(--color-text-primary))' },
            h1: {
              color: 'rgb(var(--color-text-primary))',
              fontSize: '2em',
              fontWeight: '700',
              letterSpacing: '-0.025em',
              marginTop: '2em',
              marginBottom: '0.75em',
            },
            h2: {
              color: 'rgb(var(--color-text-primary))',
              fontSize: '1.5em',
              fontWeight: '700',
              letterSpacing: '-0.02em',
              marginTop: '1.75em',
              marginBottom: '0.75em',
              paddingBottom: '0.3em',
              borderBottom: '1px solid rgba(255, 255, 255, 0.06)',
            },
            h3: {
              color: 'rgb(var(--color-text-primary))',
              fontSize: '1.25em',
              fontWeight: '600',
              marginTop: '1.5em',
              marginBottom: '0.5em',
            },
            h4: {
              color: 'rgb(var(--color-text-primary))',
              fontSize: '1.1em',
              fontWeight: '600',
              marginTop: '1.25em',
              marginBottom: '0.5em',
            },
            blockquote: {
              borderLeftColor: '#06b6d4',
              borderLeftWidth: '3px',
              color: 'rgb(var(--color-text-secondary))',
              backgroundColor: 'rgba(6, 182, 212, 0.04)',
              padding: '1rem 1.5rem',
              borderRadius: '0 0.75rem 0.75rem 0',
              fontStyle: 'normal',
              'p:first-of-type::before': { content: 'none' },
              'p:last-of-type::after': { content: 'none' },
            },
            code: {
              color: '#67e8f9',
              backgroundColor: 'rgba(6, 182, 212, 0.1)',
              border: '1px solid rgba(6, 182, 212, 0.15)',
              borderRadius: '0.375rem',
              padding: '0.15rem 0.4rem',
              fontWeight: '500',
              fontSize: '0.875em',
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            'pre code': { color: 'rgb(var(--color-text-primary))', backgroundColor: 'transparent', padding: '0', border: 'none', fontSize: 'inherit' },
            pre: { backgroundColor: 'transparent', padding: '0', margin: '0' },
            hr: { borderColor: 'rgba(255, 255, 255, 0.06)' },
            'thead th': { color: 'rgb(var(--color-text-primary))', borderBottomColor: 'rgba(255, 255, 255, 0.1)', fontWeight: '600' },
            'tbody td': { borderBottomColor: 'rgba(255, 255, 255, 0.06)' },
            img: { borderRadius: '0.75rem' },
            li: { color: 'rgb(var(--color-text-secondary))' },
            'li::marker': { color: 'rgba(6, 182, 212, 0.5)' },
            'ol > li::marker': { color: 'rgba(6, 182, 212, 0.5)' },
          },
        },
      },
      boxShadow: {
        'glow': 'var(--shadow-glow)',
        'glow-lg': 'var(--shadow-glow-lg)',
        'glow-xl': '0 0 40px rgba(6, 182, 212, 0.15)',
        'card': 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
